#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib', '4.2.1'
mod 'runthebusiness/fetchfile', '1.0.0'

mod 'boxen/puppet-homebrew',
  :git => 'https://github.com/boxen/puppet-homebrew.git'
